export const SET_MOBILE_VIEW = 'SET_MOBILE_VIEW';
export const SET_DRAWER_OPEN = 'SET_DRAWER_OPEN';
export const SET_INITIAL_RESPONSE = 'SET_INITIAL_RESPONSE';
export const EDIT_PRODUCT_QUANTITY = 'EDIT_PRODUCT_QUANTITY';